# Generated by Django 5.1 on 2024-09-14 02:27

import board.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=board.models.unique_file_path, verbose_name='사업자등록증 사진'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image10',
            field=models.ImageField(blank=True, null=True, upload_to=board.models.unique_file_path, verbose_name='설문조사 안내 캡쳐본'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image11',
            field=models.ImageField(blank=True, null=True, upload_to=board.models.unique_file_path, verbose_name='이미지 사용 정책 확인'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=board.models.unique_file_path, verbose_name='영업신고증 사진'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=board.models.unique_file_path, verbose_name='통장사본 사진'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to=board.models.unique_file_path, verbose_name='식품안전나라 영업신고 상세페이지'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to=board.models.unique_file_path, verbose_name='배민 앱 캡쳐본(메인)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to=board.models.unique_file_path, verbose_name='배민 앱 캡쳐본(상세정보)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image7',
            field=models.ImageField(blank=True, null=True, upload_to=board.models.unique_file_path, verbose_name='포스기 설치 사진'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image8',
            field=models.ImageField(blank=True, null=True, upload_to=board.models.unique_file_path, verbose_name='쿠팡이츠 스티커'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image9',
            field=models.ImageField(blank=True, null=True, upload_to=board.models.unique_file_path, verbose_name='스토어 앱 설치 사진'),
        ),
        migrations.AlterField(
            model_name='post',
            name='images',
            field=models.CharField(max_length=100, verbose_name='이미지'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
